### ISSUE TITLE
Questions about processing delays

### ISSUE THREAD

**Issue by wjcyun** [akash-rajak/Real-Time-Human-Detection-Counting#10]
Hello: 
  My recent work is to detect moving objects in video and do a closed-loop processing, so I'd like to ask how much processing latency there will be for real-time processing of video streams, or what kind of computer configuration is needed to make the latency as small as possible？ Looking forward to your answer.Thank you!

**Comment by akash-rajak** [comment]
Hi tanks for reaching me

Actually i run this model on laptop with 64 bit windows system and 8 GB RAM
but latency of the video was not that much small

One that you can do is you ca use some better algorithm(like YOLO5) with GPU installed, will give quite as small latency

Thank you

**Comment by wjcyun** [comment]
Thank you sincerely for your reply. It is a good advice for me.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akash-rajak/Real-Time-Human-Detection-Counting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月19日(星期天) 凌晨0:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [akash-rajak/Real-Time-Human-Detection-Counting] Questions about processing delays (Issue #10)





 
Hi tanks for reaching me
 
Actually i run this model on laptop with 64 bit windows system and 8 GB RAM
 but latency of the video was not that much small
 
One that you can do is you ca use some better algorithm(like YOLO5) with GPU installed, will give quite as small latency
 
Thank you
