### ISSUE TITLE
Get error on plot

### ISSUE THREAD

**Issue by winnk23** [akash-rajak/Real-Time-Human-Detection-Counting#11]
Hello 

Can I get your help as I'm getting error after detecting people when I click the 'Enumeration plot' and 'Avg. accuracy plot'. Here's the error show:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\FYP\Real-Time-Human-Detection-Counting-main\main.py", line 158, in img_enumeration_plot
    plt.get_current_fig_manager().canvas.set_window_title("Plot for Image")
AttributeError: 'FigureCanvasTkAgg' object has no attribute 'set_window_title'

Thank you.

**Comment by akash-rajak** [comment]
Hi @winnk23 ,

thanks for reaching me out

one solution i can suggest is, replace line 158 with below line
plt.manager.set_window_title("Plot for Image")

then check and reach out to me if error comes.

**Comment by winnk23** [comment]
Hi Sir,

Thanks for your reply, but still get error. The error shows:
    return self.func(*args)
  File "E:\FYP\Real-Time-Human-Detection-Counting-main\main.py", line 158, in img_enumeration_plot
    plt.manager.set_window_title("Plot for Image")
AttributeError: module 'matplotlib.pyplot' has no attribute 'manager'


After that I tried to import manager' on the top of the code and try to install manager with 'pip install manager', but get this error:
Defaulting to user installation because normal site-packages is not writeable
Collecting manager
  Downloading Manager-2.0.5.tar.gz (751 kB)
     ---------------------------------------- 751.8/751.8 kB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\MY HP\AppData\Local\Temp\pip-install-_9spgwkm\manager_52c2594075714fd49ef7efe47873f077\setup.py", line 35, in <module>
          _setEncoding()
        File "C:\Users\MY HP\AppData\Local\Temp\pip-install-_9spgwkm\manager_52c2594075714fd49ef7efe47873f077\setup.py", line 31, in _setEncoding
          reload(sys)
      NameError: name 'reload' is not defined
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by akash-rajak** [comment]
Try to update the matplotlib library to its latest version

then try to run

**Comment by winnk23** [comment]
Hi, i've upgrade the matplotlib version 
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Scripts>pip install --upgrade matplotlib
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\my hp\appdata\roaming\python\python39\site-packages (3.6.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\my hp\appdata\roaming\python\python39\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: numpy>=1.19 in c:\users\my hp\appdata\roaming\python\python39\site-packages (from matplotlib) (1.23.3)
Requirement already satisfied: pillow>=6.2.0 in c:\users\my hp\appdata\roaming\python\python39\site-packages (from matplotlib) (9.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\my hp\appdata\roaming\python\python39\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\my hp\appdata\roaming\python\python39\site-packages (from matplotlib) (4.37.3)
Requirement already satisfied: packaging>=20.0 in c:\users\my hp\appdata\roaming\python\python39\site-packages (from matplotlib) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\my hp\appdata\roaming\python\python39\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\my hp\appdata\roaming\python\python39\site-packages (from matplotlib) (1.0.5)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\my hp\appdata\roaming\python\python39\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: six>=1.5 in c:\users\my hp\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0) 

but still get the same error: 
    return self.func(*args)
  File "E:\FYP\Real-Time-Human-Detection-Counting-main\main.py", line 158, in img_enumeration_plot
    plt.manager.set_window_title("Plot for Image")
**AttributeError: module 'matplotlib.pyplot' has no attribute 'manager'**
