### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by dhinesh-kM** [akash-rajak/Real-Time-Human-Detection-Counting#13]
Tensorflow 2.10 is enough for this project.
Pip install tensorflow in cmd is enough for install tensorflow.In some website they tell to install miniconda.  how can I install tensorflow please provide a proper guide.

**Comment by akash-rajak** [comment]
Hi @dhinesh-kM

Thanks for reaching out
Yes, Pip install tensorflow in cmd is not enough for installation of tensorflow

I followed the below youtube link inorder to install it
Try installing using this link : [Link](https://www.youtube.com/watch?v=hHWkvEcDBO0)

**Comment by ALEN2002-py** [comment]
Hi how to install persondetection library

**Comment by ALEN2002-py** [comment]
Hi how to install persondetection library
