### ISSUE TITLE
LICENSE for this project

### ISSUE THREAD

**Issue by KelvinHong** [akash-rajak/Real-Time-Human-Detection-Counting#15]
Hi, this is an amazing project! I'm just curious do you plan on adding a license for this, so I can credit your project correctly? Thanks.

**Comment by KelvinHong** [comment]
> Hi @KelvinHong
> 
> Thanks for reaching Yes I can add the license.

Thank you!

**Comment by akash-rajak** [comment]
You mean adding license like `MIT License` or the sponsor button?

**Comment by KelvinHong** [comment]
Adding a MIT License will be good, although that depends on how you think people should be using your repository.

**Comment by akash-rajak** [comment]
Alright, I was thinking about MIT only,

Will let you know, once I add it

**Comment by akash-rajak** [comment]
I have added the MIT License, you can check it

**Comment by KelvinHong** [comment]
It's wonderful. Thank you!
